name: maddpg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - numpy
  - matplotlib
  - tensorboard
  - pip:
      - gymnasium
      - "pettingzoo[mpe]"
      - supersuit
      - tqdm
      - imageio
